name: better_internet_checker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

dependencies: 
  http: ^0.13.5

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
